name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pip3 install pylint
          pylint --rcfile .pylintrc site memba
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "memba" #Must be unique in Heroku
          heroku_email: "aronchick@gmail.com"
